package js.webgl2;

/**
TransformFeedback enables transform feedback, which is the process of capturing primitives generated by vertex processing.
It allows to preserve the post-transform rendering state of an object and resubmit this data multiple times.

The TransformFeedback object does not define any methods or properties of its own and its content is not directly accessible.
When working with TransformFeedback objects, the following methods of the `RenderingContext2` are useful:

* `RenderingContext2.createTransformFeedback()`
* `RenderingContext2.deleteTransformFeedback()`
* `RenderingContext2.isTransformFeedback()`
* `RenderingContext2.bindTransformFeedback()`
* `RenderingContext2.beginTransformFeedback()`
* `RenderingContext2.endTransformFeedback()`
* `RenderingContext2.pauseTransformFeedback()`
* `RenderingContext2.resumeTransformFeedback()`
* `RenderingContext2.transformFeedbackVaryings()`
* `RenderingContext2.getTransformFeedbackVarying()`

More information at <https://developer.mozilla.org/en-US/docs/Web/API/WebGLTransformFeedback>.
**/
@:native("WebGLTransformFeedback")
extern class TransformFeedback
{
}
